version: '3.8'

services:
  app:
    build: .
    container_name: fullstack-app
    ports:
      - "8443:443"  # SSL на 8443
    networks:
      - app-network

networks:
  app-network:
    driver: bridge