version: '3.8'

services:
  app:
    build: .
    container_name: fullstack-app
    ports:
      - "80:80"
      - "8443:443"  # Меняем внешний порт на 8443, чтобы не конфликтовать
    networks:
      - app-network

networks:
  app-network:
    driver: bridge