version: '3.8'

services:
  app:
    build: .
    container_name: fullstack-app
    ports:
      - "80:80"
      - "443:443"  # Добавляем порт для HTTPS
    volumes:
      - ./letsencrypt:/etc/letsencrypt  # Для хранения сертификатов Let's Encrypt
      - ./webroot:/usr/share/nginx/html  # Для Let's Encrypt challenge
    networks:
      - app-network

networks:
  app-network:
    driver: bridge